version: "3.8"

services:
  skbookbot:
    build: .
    container_name: skbookbot
    restart: unless-stopped
    ports:
      - "5200:5200"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./plugins:/app/plugins
      - ./.env:/app/.env
    environment:
      - TZ=Asia/Shanghai